config/routes.rb
KepplerBlog::Engine.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

	 scope :admin, :blog do
  	resources :posts do 
      get 'find/subcategories', action: :subcategories_of_cagegory, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: 'search'
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :categories do
      get '(page/:page)', action: :index, on: :collection, as: 'search'
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
  end

  scope :blog do
    get '(page/:page)', to: 'blog#index', as: :blog_listing
    get ":type/:permalink", to: 'blog#filter', as: :filter
    get "category/:category/subcategory/:subcategory", to: 'blog#filter_subcategory', as: :filter_subcategory
    get '/:permalink', to: 'blog#show', as: :blog_show_post
  end

end

app/models/keppler_blog/category.rb
module KepplerBlog
  class Category < ActiveRecord::Base
    include ElasticSearchable
    include ActivityHistory
    before_save :create_permalink
    has_many :posts, dependent: :destroy
    has_many :subcategories
    accepts_nested_attributes_for :subcategories, :reject_if => :all_blank, :allow_destroy => true

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :name, :subcategories] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        subcategories: self.subcategories.map { |subcategory| subcategory.name } .join(", ")
      }.as_json
    end

    private

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

  end
end

app/models/keppler_blog/post.rb
module KepplerBlog
  class Post < ActiveRecord::Base
    include ElasticSearchable
    include ActivityHistory
    before_save :create_permalink
    mount_uploader :image, ImageUploader
    belongs_to :user
    belongs_to :category
    belongs_to :subcategory
    acts_as_taggable
    acts_as_taggable_on :tags

    validates_presence_of :title, :body, :category_id
    validates_uniqueness_of :title

    def self.published
      where(public: true).order(created_at: :desc)
    end

    def self.filter_by_autor(autor)
      where(public: true, user: User.find_by_permalink(autor).id).order(created_at: :desc)
    end

    def self.filter_by_category(category)
      where(public: true, category: Category.find_by_permalink(category).id).order(created_at: :desc)
    end

    def self.filter_by_tag(tag)
      where(public: true).tagged_with(tag.gsub("-", " ")).order(created_at: :desc)
    end

    def self.filter_by_subcategory(category, subcategory)
      Category.find_by_permalink(category).subcategories.find_by_permalink(subcategory).posts.order(created_at: :desc)
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :title, :body, :category, :autor, :subcategory, :public, :comments, :shared, :tags], operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        title: self.title,
        body: ActionView::Base.full_sanitizer.sanitize(self.body, tags: []),
        autor: self.user.name,
        category: self.category.name,
        subcategory: self.subcategory ? self.subcategory.name : "--subcategoria",
        public: self.public ? "si--publicado" : "no--publicado",
        comments: self.comments_open ? "si--comentarios" : "no--comentarios",
        shared: self.shared_enabled ? "si--compartiendo" : "no--compartiendo",
        tags: self.tag_list.to_s
      }.as_json
    end

    private

    def create_permalink
      self.permalink = self.title.downcase.parameterize
    end

  end
  #Post.import
end

app/models/keppler_blog/subcategory.rb
module KepplerBlog
  class Subcategory < ActiveRecord::Base
  	before_save :create_permalink
  	belongs_to :category
  	has_many :posts

  	private
  	
  	def create_permalink
      self.permalink = self.name.downcase.parameterize
    end
  end
end

app/controllers/keppler_blog/application_controller.rb
module KepplerBlog
  class ApplicationController < Admin::AdminController
  end
end

app/controllers/keppler_blog/blog_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class BlogController < App::AppController
    layout 'app/layouts/application'
    before_action :set_data_widgets, only: [:index, :show, :filter, :filter_subcategory]

    def index
      @posts = Post.searching(params[:query]).where(public: true).page(@current_page).per(KepplerBlog.posts_per_page)
    end

    def show
      @post =  Post.find_by_permalink(params[:permalink])
    end

    def filter
      @posts = Post.send("filter_by_#{params[:type]}", params[:permalink]).page(@current_page).per(10)
      render action: 'index'
    end

    def filter_subcategory
      @posts = Post.filter_by_subcategory(params[:category], params[:subcategory]).page(@current_page).per(10)
      render action: 'index'
    end

    private

    def set_data_widgets
      @posts_recents = Post.where(public: true).order("created_at DESC").first(6)
      @categories = Category.all.order(:name)
    end

  end
end

app/controllers/keppler_blog/categories_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class CategoriesController < Admin::AdminController
    before_filter :authenticate_user!
    layout 'admin/layouts/application'
    load_and_authorize_resource
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /categories
    def index
      categories = Category.searching(@query).all
      @objects, @total = categories.page(@current_page), categories.size
      redirect_to categories_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect(@category, params)
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect(@category, params)
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: actions_messages(@category)
    end

    def destroy_multiple
      Category.destroy redefine_ids(params[:multiple_ids])
      redirect_to categories_path(
        page: @current_page, search: @query
      ), notice: actions_messages(Category.new)
    end

    private

    # Get submit key to redirect, only [:create, :update]
    def redirect(object, commit)
      if commit.key?('_save')
        redirect_to(object, notice: actions_messages(object))
      elsif commit.key?('_add_other')
        redirect_to(
          new_category_path,
          notice: actions_messages(object)
        )
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name, subcategories_attributes: [:id, :name, :_destroy])
    end

    def show_history
      get_history(Category)
    end
  end
end

app/controllers/keppler_blog/posts_controller.rb
# Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class PostsController < Admin::AdminController
    before_filter :authenticate_user!
    layout 'admin/layouts/application'
    load_and_authorize_resource except: [:subcategories_of_cagegory]
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :set_categories, only: [:new, :edit, :update, :create]
    before_action :show_history, only: [:index]

    # GET /posts
    def index
      posts = current_user.has_role?(:autor) ? Post.searching(@query).where(user_id: current_user.id) : Post.searching(@query).all
      @objects, @total = posts.page(@current_page), posts.size
      redirect_to posts_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
      @post = Post.new(post_params.merge(user_id: current_user.id))

      if @post.save
        redirect(@post, params)
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      @post.subcategory_id = nil if post_params[:subcategory_id].nil?

      if @post.update(post_params)
        redirect(@post, params)
      else
        render :edit
      end
    end


    def subcategories_of_cagegory
      @category = Category.find(params[:category_id])
      @subcategories = @category.subcategories
      respond_to do |format|
         format.js {  }
      end
    end


    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: actions_messages(@post)
    end

    def destroy_multiple
      Post.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        posts_path(page: @current_page, search: @query),
        notice: actions_messages(Post.new)
      )
    end

    private

    # Get submit key to redirect, only [:create, :update]
    def redirect(object, commit)
      if commit.key?('_save')
        redirect_to(object, notice: actions_messages(object))
      elsif commit.key?('_add_other')
        redirect_to(
          new_post_path,
          notice: actions_messages(object)
        )
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_categories
      @categories = Category.order(:name)
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(
        :title, :body, :user_id, :category_id,
        :subcategory_id, :image, :public, :comments_open,
        :shared_enabled, :permalink, :tag_list
      )
    end

    def show_history
      get_history(Post)
    end
  end
end

app/helpers/keppler_blog/application_helper.rb
module KepplerBlog
  module ApplicationHelper
 
  end
end

app/views/keppler_blog/blog/_categories.html.haml
%nav.navbar#navbar-categories.hidden-xs
	.container-fluid
		.collapse.navbar-collapse
			%ul.nav.navbar-nav
				- @categories.each do |category|
					- unless category.posts.count.zero?
						%li.dropdown
							= link_to filter_path('category', category.permalink), class: "dropdown-toggle #{'active' if category.permalink.eql?(params[:permalink]) or category.permalink.eql?(params[:category])}" ,"aria-expanded" => false, "aria-haspopup" => true, "data-toggle" => "dropdown disabled", :role => "button" do
								= category.name.titleize
								%span.caret
							- unless category.subcategories.empty?
								%ul.dropdown-menu
									- category.subcategories.each do |subcategory|
										- unless subcategory.posts.count.zero?
											%li
												= link_to subcategory.name, filter_subcategory_path(category.permalink, subcategory.permalink), class: "#{'active' if category.permalink.eql?(params[:category]) and subcategory.permalink.eql?(params[:subcategory])}"

app/views/keppler_blog/blog/_comments_facebook.html.haml
- if @post.comments_open
	.fb-comments{ 'data-href' => "#{request.url}",  'data-numposts' => "5", 'data-colorscheme' => "light", "data-width" => "100%", "data-version"=>"v2.4" }

app/views/keppler_blog/blog/_facebook_comments.html.haml
- if @post.comments_open
	.fb-comments{ 'data-href' => "#{request.url}",  'data-numposts' => "5", 'data-colorscheme' => "light", "data-width" => "100%", "data-version"=>"v2.4" }

app/views/keppler_blog/blog/_recents.html.haml
.blog-widget
	.blog-widget--header
		%h3.widget-title
			Recientes
	.blog-widget--body
		%ul.widget-list#recents
			- @posts_recents.each do |post|
				%li
					%i.fa.fa-sign-out
					= link_to post.title, blog_show_post_path(post.permalink)

app/views/keppler_blog/blog/_search.html.haml
.blog-widget
	.blog-widget--header.hidden-xs
		%h3.widget-title
			Búsqueda
	.blog-widget--body
		.widget-list#search
			= form_tag blog_listing_path, method: :get, :html => {:class => ""} do |f|
				= text_field_tag :query, params[:query], :placeholder => "Buscar.."

app/views/keppler_blog/blog/_sidebar.html.haml
.col-lg-4.hidden-xs
	= render 'search'
	= render 'recents'
	= render 'tags'
	= render 'twitter_timeline'

app/views/keppler_blog/blog/_tags.html.haml
.blog-widget
	.blog-widget--header
		%h3.widget-title
			Tags
	.blog-widget--body
		%ul.widget-list#tags
			- ActsAsTaggableOn::Tag.most_used(9).each do |tag|
				%li
					= link_to filter_path("tag", tag.name.parameterize), class: "tag #{'active' if params[:permalink] and tag.name.downcase.eql?(params[:permalink].gsub("-", " ").downcase)}" do
						%i.fa.fa-tags
						= tag.name

app/views/keppler_blog/blog/_twitter_timeline.html.haml
.blog-widget
	.blog-widget--header
		%h3.widget-title
			Twitter timeline
	.blog-widget--body
		%a.twitter-timeline{ href:"https://twitter.com/#{KepplerBlog.twitter_username}", "data-widget-id"=>"#{KepplerBlog.widget_twitter_id}", "data-chrome"=>"header" } 
			= "Tweets por @#{KepplerBlog.twitter_username}"
		

app/views/keppler_blog/blog/index.html.haml
= title "Keppler Blog"
= meta_description "Bienvenidos al blog de keppler admin, aquí podras encontrar excelentes articulos sobre ruby on rails."

.container.keppler-blog#keppler-blog
	= render 'categories'
	.visible-xs
		= render 'search'
	.row
		.col-lg-8.col-xs-12
			.posts-wrapper
				- unless @posts.empty?
					- @posts.each do |post|
						.post
							%h2.post-title
								= link_to post.title, blog_show_post_path(post.permalink)
							.post-attributes
								%ul
									%li
										%span
											%i.fa.fa-calendar
											= post.created_at.strftime("%d %b. %Y")
									%li
										%i.fa.fa-user
										= link_to post.user.name, filter_path('autor', post.user.permalink)
									%li
										%i.fa.fa-tags
										= link_to post.category.name, filter_path('category', post.category.permalink)
							.post-image
								= link_to blog_show_post_path(post.permalink) do
									= image_tag post.image
							.post-body
								= sanitize(post.body, tags: []).truncate(300)
								.read-more
									= link_to "Leer más", blog_show_post_path(post.permalink), class: "btn btn-xs"
						%hr.hr-half
				- else
					%center
						No se encontraron resultados.
					%hr.hr-half

				= paginate @posts, :views_prefix => 'templates'

		= render "sidebar"

app/views/keppler_blog/blog/show.html.haml
= title @post.title
= meta_description sanitize(@post.body, tags: []).truncate(150)

.container.keppler-blog#keppler-blog
	= render 'categories'
	.visible-xs
		= render 'search'
	.row
		.col-lg-8.col-xs-12
			.posts-wrapper
				.post
					%h2.post-title
						= link_to @post.title, blog_show_post_path(@post.permalink, popup: "true")
					.post-attributes
						%ul
							%li
								%span
									%i.fa.fa-calendar
									= @post.created_at.strftime("%d %b. %Y")
							%li
								%i.fa.fa-user
								= link_to @post.user.name, filter_path('autor', @post.user.permalink)
							%li
								%i.fa.fa-tags
								= link_to @post.category.name, filter_path('category', @post.category.permalink)
					.post-image
						= link_to blog_show_post_path(@post.permalink) do
							= image_tag @post.image
					= @post.shared_enabled ? social_share_button_tag(@post.title) : "<br>".html_safe
					.post-body
						= @post.body.html_safe

				= render 'facebook_comments'

		= render "sidebar"